---
title: "Desigualdades nos acessos às Ciências Sociais:"
subtitle: "O papel da raça, renda e escolaridade na aprovação do vestibular"
author:
  - name: Artur Damião
    orcid: 0000-0002-8628-1653
    email: arturcardoso@usp.br
    affiliation: Departamento de Sociologia
  - name: Isabella da Nóbrega
    affiliation: Faculdade de Filosofia, Letras e Ciências Humanas
    email: isabelladanobrega@usp.br
  - name: Gabriella Medeiros
    affiliation: Faculdade de Filosofia, Letras e Ciências Humanas
    email: gabriella.medeiros@usp.br
  - name: Maria Eduarda
    affiliation: Faculdade de Filosofia, Letras e Ciências Humanas
    email: sduda8958@usp.br
  - name: Yasmin Flor
    affiliation: Faculdade de Filosofia, Letras e Ciências Humanas
    email: floryasmin861@usp.br

keywords: 
  - Estratificação educacional
  - Ensino superior
  - Capital cultural

lang: pt
format:
  html:
    css: justificado.css
---

## Introdução e contextualização

Considerando que o questionário PET consegue capturar somente informações acerca dos estudantes que já ingressaram na carreira de Ciências Sociais, avaliamos que é interessante analisar, também, o perfil daqueles alunos que prestaram o vestibular da FUVEST e escolheram a carreira de Ciências Sociais, tendo sido aprovados ou não. Quais sãos os elementos importantes que são responsáveis pela aprovação do aluno nesta carreira. 

Com isso em mente, estabelecemos, portanto, a seguinte pergunta de pesquisa: **como a renda, raça e o tipo de escola inlfuenciam o ingresso de alunos cotistas e não cotistas na carreira de Ciências Sociais da Universidade de São Paulo**? Para as variáveis analisadas, estabelecemos:

| Variável              | Tipo                  | Categoria/Descrição |
|-----------------------|----------------------|---------------------|
| **Aprovação no vestibular** | Binária | 1 = Aprovado na carreira de Ciências Sociais pela FUVEST <br> 0 = Não aprovado |
| **Raça** | Categórica (dummy) | 0 = Branco (referência)  <br> 1 = Preto/Pardo/Indígena |
| **Renda familiar** | Contínua| Faixas de renda em salários mínimos |
| **Escolaridade dos pais** | Ordinal| 1 = Baixa (até ensino fundamental completo)  <br> 2 = Média (ensino médio completo) <br> 3 = Alta (ensino superior completo ou mais) |
| **Tipo de escola** | Categórica (dummy) | 0 = Escola pública (referência)  <br> 1 = Escola privada |


Para compreender o impacto de cada uma das variáveis, estabelecemos o seguinte modelo de regressão logística:


$$
\log \left(\frac{P(Aprovado=1)}{1 - P(Aprovado=1)}\right) = \beta_0 + \beta_1 \text{Raça} + \beta_2 \text{Renda} + \beta_3 \text{EscolaridadePais} + \beta_4 \text{TipoEscola} + \varepsilon
$$

 
## Hipóteses de pesquisa
Frente ao exposto, consideramos as seguintes hipóteses:

**H~0~**: Raça, renda e tipo de escola não influenciam o ingresso de estudantes na carreira de Ciências Sociais. 
**H~1~**: A renda familiar e a escolaridade dos pais (proxy para capital cultural) aumentam as chances de ingresso (analisar dados da FUVEST, comparando os inscritos na carreira X perfil presente no curso, via questionário PET).  
**H~2~**: Alunos oriundos de escolas privadas têm maior probabilidade de ingressar sem necessidade de cotas, mesmo em grupos de baixa renda.


No contexto da análise das hipóteses propostas, o objetivo é investigar como variáveis sociodemográficas, como raça, renda familiar e tipo de escola, influenciam o ingresso de estudantes na carreira de Ciências Sociais. A hipótese nula (**H~0~**) sugere que essas variáveis não têm impacto significativo sobre a aprovação no vestibular, implicando que fatores como a origem socioeconômica dos candidatos não determinariam as suas chances de ingresso. Para testar essa hipótese, compararemos as características dos estudantes inscritos na FUVEST para a carreira de Ciências Sociais com o perfil dos alunos já aprovados, a partir dos dados do questionário PET.

Por outro lado, a hipótese alternativa (**H~1~**) propõe que a renda familiar e a escolaridade dos pais (como proxy para o capital cultural) têm um efeito positivo nas chances de ingresso, favorecendo candidatos com maior capital cultural. A relação entre essas variáveis e o ingresso será analisada por meio do modelo de regressão apresentado, verificando a consistência e a força dessa associação nos dados coletados. Comparando o perfil dos inscritos com o dos aprovados, será possível avaliar a influência desses fatores no processo seletivo e nas desigualdades de acesso à educação superior.


